import Head from 'next/head'
import IntroHeader from "../components/IntroHeader";
import RecentPosts from '../components/RecentPosts';
import FeaturedWorks from '../components/FeaturedWorks';
import { getAllPosts, getAllWork } from '../../lib/api';

export async function getStaticProps() {
  const posts = getAllPosts();
  const work = getAllWork();

  return {
    props: {
      posts,
      work,
    }
  }
}

export default function Home({ posts, work }) {
  return (
    <div>
      <Head>
        <title>NextJS Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <IntroHeader />
        <RecentPosts posts={posts}/>
        <FeaturedWorks work={work}/>
    </div>
  )
}