import FeaturedWorks from '@/components/FeaturedWorks'
import IntroHeader from '@/components/IntroHeader'
import RecentPosts from '@/components/RecentPosts'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>NextJS Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        {/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <IntroHeader />
      <RecentPosts />
      <FeaturedWorks />
    </>
  )
}
